### ISSUE TITLE
how to add this type of rule in whitelist

### ISSUE THREAD

**Issue by rickygm** [wargio/naxsi#100]
I have several systems developed with aspx.net and naxsi is blocking me a lot:

`NAXSI_FMT: ip=208.96.135.x&server=app.domain.com&uri=/Solicitud/Solicitar.aspx&config=block&rid=38507c49cfc158851449c822ac16226b&cscore0=$UPLOAD&score0=8&zone0=FILE_EXT&id0=1501&var_name0=ctl00%24ContentPlaceHolder1%24FileUpload `

`2023/09/18 12:16:07 [error] 77012#77012: NAXSI_FMT: ip=104.28.145.x&server=app2.domain.com&uri=/Empresa/11Documentos.aspx&config=block&rid=0fea665b14581102c716b66028155b29&cscore0=$UPLOAD&score0=8&zone0=FILE_EXT&id0=1501&var_name0=ctl00%24ContentPlaceHolder1%24FileUpload`

For example, add these like this, but I'm not sure it works at all, and I may have to add other urls again.

```
BasicRule wl:1501 "mz:$URL:/Solicitud/Solicitar.aspx|FILE_EXT";
BasicRule wl:1501 "mz:$URL:/SiGAT/Planes.aspx|FILE_EXT";
BasicRule wl:1501 "mz:$URL:/Solicitudes/wfSolicitud.aspx|FILE_EXT";
BasicRule wl:1501 "mz:$URL:/Empresa/11Documentos.aspx|FILE_EXT";
```

any idea?

**Comment by wargio** [comment]
The triggered rule is `uploaded filename contains non-printable ascii chars` (see below)
```
MainRule "rx:^[\.a-z0-9_\- ]+$" negative "msg:uploaded filename contains non-printable ascii chars" "mz:FILE_EXT" "s:$UPLOAD:8" id:1501;
```
Judging from the logs and the whitelist rules i would say that you probably have people uploading files with non ascii characters (spanish accents are those triggering the rule, probably).

The rules you have implemented looks good and they should work (unless you get a different rule triggered).
I also strongly suggest (for your sanity) to enable [json logging](https://github.com/wargio/naxsi/blob/main/unit-tests/tests/35log_json.t#L23).

**Comment by rickygm** [comment]
Thanks Wargio, I will keep it in mind, just one more question, some way to abbreviate this rule to avoid future blockages. There are around 10 systems and this generates many lines of code in the whitelist.

**Comment by wargio** [comment]
if the issue is that there are going to be always files with accents etc.. then just whitelist the rule in a more global way:
`BasicRule wl:1501 "mz:FILE_EXT";`
