### ISSUE TITLE
Bookworm package and PCRE version

### ISSUE THREAD

**Issue by vcr-j** [wargio/naxsi#105]
Hello,

The debian package v1.6 for bookworm does not work with the default bookworm nginx package.
I've installed debian-bookworm-libnginx-mod-http-naxsi_1.6_amd64.deb and nginx-full ( nginx v1.22.1).

When starting nginx I get an error: 'dlopen() ```/usr/share/nginx/modules/ngx_http_naxsi_module.so" failed (/usr/share/nginx/modules/ngx_http_naxsi_module.so: undefined symbol: pcre_exec) in /etc/nginx/modules-enabled/50-mod-http-naxsi.conf:1```

It's look like the package is build with the old pcre library and not pcre2, nginx v1.22 is built with pcre2.
The package dependency explicitly state the old pcre lib: https://github.com/wargio/naxsi/blob/f74611640b76a798cdedcc3fa1147b69eaac969f/distros/deb/control.install#L5C1-L5C83

It looks like naxsi support PCRE2: https://github.com/wargio/naxsi/blob/f74611640b76a798cdedcc3fa1147b69eaac969f/naxsi_src/naxsi_runtime.c#L99C14-L99C14

Shouldn't the bookworm package be compiled with the pcre2 library?

Thanks

**Comment by wargio** [comment]
yes it should. thanks for reporting this.

**Comment by wargio** [comment]
@vcr-j i have updated the built debs. it should be correct now. thanks for noticing the issue.

**Comment by vcr-j** [comment]
Thanks a lot, the install is working fine now.
