### ISSUE TITLE
libinjection.pc package not found

### ISSUE THREAD

**Issue by ganlei333** [wargio/naxsi#121]
configuring additional dynamic modules
adding module in ../naxsi_src/
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Using submodule libinjection

**Comment by wargio** [comment]
It is normal that while building it may output that. there is a check to see if `libinjection` is installed system wide (like on fedora) and if it is, then it will try to use that module instead of using the one within the submodules.

If it fails to build, did you follow the build steps here https://github.com/wargio/naxsi#build-naxsi ?

**Comment by duy13** [comment]
Same problem, I can't install something called `libinjection` on ubuntu 20 + nginx 1.24. Do you have any instructions for this package?

```
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Cannot find 'libinjection' submodule.
```

**Comment by wargio** [comment]
the reason why you cannot build is because you didn't follow the instructions on how to build the repo and did not fetch the submodule.

either `git clone --recurse-submodules https://github.com/wargio/naxsi.git` or `git submodule init && git submodule update`

**Comment by wargio** [comment]
that is weird. did you try to do a clean build? also what OS are you using? can you provide me the configuration parameters that you have used to generate this broken build?
