### ISSUE TITLE
Error when run make

### ISSUE THREAD

**Issue by tapsu01** [wargio/naxsi#123]
Hi, when I run `make`, I get response error below, please check for me, thank you.
**Details**

- NGINX version: `1.20.1`
- NAXSI version: `1.6`
- Did you install NAXSI from a package manager? **NO**. I get naxsi from https://github.com/wargio/naxsi/releases
- Operating System: `CentOS 7 Linux`

**Nginx Logs**

```
../naxsi/naxsi_src/naxsi_utils.c: In function ‘naxsi_is_illegal_host_name’:
../naxsi/naxsi_src/naxsi_utils.c:1170:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 1; i < plen; ++i) {
   ^
../naxsi/naxsi_src/naxsi_utils.c:1170:3: note: use option -std=c99 or -std=gnu99 to compile your code
../naxsi/naxsi_src/naxsi_utils.c:1196:15: error: redefinition of ‘i’
   for (size_t i = 0; i < n_cidrs; ++i) {
               ^
../naxsi/naxsi_src/naxsi_utils.c:1170:15: note: previous definition of ‘i’ was here
   for (size_t i = 1; i < plen; ++i) {
               ^
../naxsi/naxsi_src/naxsi_utils.c:1196:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < n_cidrs; ++i) {
   ^
../naxsi/naxsi_src/naxsi_utils.c: In function ‘naxsi_generate_request_id’:
../naxsi/naxsi_src/naxsi_utils.c:1219:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < len; i++) {
   ^
make[1]: *** [objs/addon/naxsi_src/naxsi_utils.o] Error 1

```

**Comment by wargio** [comment]
which version of gcc are you using?

**Comment by tapsu01** [comment]
> which version of gcc are you using? also add this to the `CFLAGS`: `-std=gnu99`

I use gcc version 4.8.5

**Comment by wargio** [comment]
that is very old. anyway if you pass `CFLAGS="-std=gnu99" ./configure  --prefix=/etc/nginx --add-dynamic-module=../naxsi/naxsi_src` it should compile.

**Comment by tapsu01** [comment]
> that is very old. anyway if you pass `CFLAGS="-std=gnu99" ./configure --prefix=/etc/nginx --add-dynamic-module=../naxsi/naxsi_src` it should compile.

Tks you very much, I compiled success.
