### ISSUE TITLE
Question for testing about Thesis

### ISSUE THREAD

**Issue by IsmaelMagro21** [wargio/naxsi#126]
Good afternoon, I hope you are well. I am a final year student currently studying for my Bachelor's degree in Computing and Business and for my thesis I was aiming to create and use a virtual testing environment using Oracle VirtualBox to be able to host various web applications extracted from OWASP Juice shop. The locally hosted testing environment will be made available on the internet and be given a domain from GoDaddy. Furthermore, the testing environment will be exposed to several predefined attacks using Kali Linux, which include but are not limited to SQL Injection, DoS attacks and broken authentication. These attacks will be launched against three different web application firewalls, Cloudflare, Azure WAF and NAXSI. Hence, in total there will be 3 domains which will be public, one for each. Kindly note that the virtual machines will be hosted locally on my laptop. Would this be allowed please since it is for educational purposes and hosted locally?

**Comment by wargio** [comment]
Ehm yes for Naxsi.
You can deploy it for personal use, as for commercial use and ofc for research use.
Also keep in mind that naxsi usually requires to be configured following whatever you are hosting.
