### ISSUE TITLE
Naxsi module version mismatch with NGINX version

### ISSUE THREAD

**Issue by hengyinice** [wargio/naxsi#127]
What is the highest version of NGINX that naxsi-1.3 can support? I tried to install naxsi on NGINX-1.22 reporting version error
The error is as follows：
[emerg] 10#10: module "/usr/share/nginx/modules/ngx_http_naxsi_module.so" version 1018000 instead of 1022001 in /etc/nginx/modules-enabled/50-mod-http-naxsi.conf:1

**Comment by wargio** [comment]
don't use naxsi 1.3, use the latest one (1.6).

Your issue seems related to an old version of naxsi trying to be executed on a newer version of NGINX.

You need to build the module for the correct version of nginx.
