### ISSUE TITLE
No package 'libinjection' found

### ISSUE THREAD

**Issue by peaceanddemocracy** [wargio/naxsi#131]
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for sysconf(_SC_LEVEL1_DCACHE_LINESIZE) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional dynamic modules
adding module in ../naxsi/naxsi_src
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Package libinjection was not found in the pkg-config search path.
Perhaps you should add the directory containing `libinjection.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libinjection' found
Cannot find 'libinjection' submodule.

CentOS 6.8

**Comment by wargio** [comment]
you either didn't follow the instructions when cloning the repository https://github.com/wargio/naxsi?tab=readme-ov-file#build-naxsi or used the tar/zip release from github which doesn't include the the required submodules.

If you use the tarball release please be sure to download the one ending with `-with-deps`
