### ISSUE TITLE
$naxsi_request_id is not populated

### ISSUE THREAD

**Issue by viiftw** [wargio/naxsi#142]
**Details**

- NGINX version: `1.24.0, 1.26.0`
- NAXSI version: `1.6`
- Did you install NAXSI from a package manager? **NO**
- Operating System: `Ubuntu 20`

**Nginx config**

```
server {
    listen       80;
    server_name  localhost;
    SecRulesEnabled;
    LibInjectionSql;
    LibInjectionXss;
    DeniedUrl "/RequestDenied";
    CheckRule "$SQL >= 8" BLOCK;
    CheckRule "$RFI >= 8" BLOCK;
    CheckRule "$TRAVERSAL >= 4" BLOCK;
    CheckRule "$EVADE >= 4" BLOCK;
    CheckRule "$XSS >= 8" BLOCK;

    set $naxsi_json_log 1;
    set $naxsi_extensive_log 1;

    location /RequestDenied {
        add_header Content-Type 'text/html; charset=utf-8';
        return 200 "WAF interception：$naxsi_server - $naxsi_request_id $naxsi_match $naxsi_attack_action";
    }

    location / {
        root   html;
        index  index.html index.htm;
    }
}
```

**Nginx logs**

```
2024/06/13 09:53:32 [error] 12979#0: *1 {"ip":"127.0.0.1","server":"localhost","rid":"01c36e29c658b75c52980f009967920c","uri":"/","id":1013,"zone":"ARGS","var_name":"q","content":"'"}, client: 127.0.0.1, server: localhost, request: "GET /?q=%27 HTTP/1.1", host: "localhost"
2024/06/13 09:53:32 [error] 12979#0: *1 {"ip":"127.0.0.1","server":"localhost","uri":"/","config":"block","rid":"01c36e29c658b75c52980f009967920c","cscore0":"$SQL","score0":"4","cscore1":"$XSS","score1":"8","zone0":"ARGS","id0":"1013","var_name0":"q"}, client: 127.0.0.1, server: localhost, request: "GET /?q=%27 HTTP/1.1", host: "localhost"
```

**Additional details**

I checked the documentation about DeniedUrl  
https://github.com/wargio/naxsi/blob/main/docs/requestdenied-bnf.md

The headers that are forwarded to the location denied page are:  
Naxsi orig url : x-orig_url header  
Naxsi orig args : x-orig_args header  
Naxsi orig sig : x-naxsi_sig header

but i am not getting those headers in the response  
![image](https://github.com/wargio/naxsi/assets/40587722/f1caab94-1038-4a9d-a0b7-d13d443217d4)

I also found a similar issues but no response  
https://github.com/nbs-system/naxsi/issues/474

One more thing, I try to display naxsi's variables, but request id(rid) is not displayed
![image](https://github.com/wargio/naxsi/assets/40587722/6dea87b3-8f50-47e0-9ddf-80c6f87f0caa)

**Comment by wargio** [comment]
because it is an internal redirect.

**Comment by viiftw** [comment]
Thank you for your quick response
My aim is to display a correlation id (or correlation header) with the naxsi log on the DeniedUrl page like this
https://github.com/nbs-system/naxsi/issues/571  
https://github.com/nbs-system/naxsi/issues/622  
Is there any way for me to do that?

**Comment by wargio** [comment]
maybe check the logs? it should always be there. regarding the fact that it is not available there, maybe is related to the redirect? not sure. looks like a bug, but the invocation is the same as for the other variables.

**Comment by viiftw** [comment]
yes log works fine but that variable doesn't

**Comment by lubomudr** [comment]
Hi

That's right

This is because an internal redirection is made to the error page and the context is cleared
To return it, you need to run through the chain of pool cleanup handlers, which is done by calling _recover_request_ctx_ (from _naxsi_skeleton.c_)

It would be nice to replace the rest of the variable calling code with
```
  ctx = ngx_http_get_module_ctx(r, ngx_http_naxsi_module);
    
  if (ctx == NULL && (r->internal || r->filter_finalize)) {
    for (cln = r->pool->cleanup; cln; cln = cln->next) {
      if (cln->handler == ngx_http_module_cleanup_handler) {
        ctx = cln->data;
        break;
      }
    }
  }
```
on call
` ngx_http_request_ctx_t* ctx = recover_request_ctx(r);
`

Prepare a patch?

**Comment by lubomudr** [comment]
And this is just the first bad news :cry: 

The second is that $naxsi_request_id does not match the NGINX $request_id variable

And what's even worse is that $naxi_request_id is ALWAYS calculated for each request, calling a rather expensive function for obtaining a random number.
In NGINX, $request_id is calculated only on demand (and is not stored in service structures, only in the variable cache)

Perhaps this needs to be fixed?
