### ISSUE TITLE
URL_X matchzone don't work in whitelist rule when mixed with FILE_EXT

### ISSUE THREAD

**Issue by LopEared** [wargio/naxsi#160]
**Details**

- NGINX version: `1.26.2`
- NAXSI version: `X.Y`
- Did you install NAXSI from a package manager? **NO** Build  by download repo.
- Operating System: `RockyLinux 8.9 Linux`

**Nginx Logs**
```
024/12/05 15:39:07 [error] 1403000#1403000: *230099211 NAXSI_FMT: ip=37.215.37.90&server=domen.name&uri=%2Fevent%2F09-01-svedeniya-o-dohodah-fizicheskih-lits-za-2024-god-poryadok-zapolneniya-i-predstavleniya-nalogovymi-agentami-v-2025-godu%2F%2520target%3D_blank%2520rel%3D%2520noopener%2520noreferrer%2520%253E%25D0%25A1%25D0%25B2%25D0%25B5%25D0%25B4%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2520%25D0%25BE%2520%25D0%25B4%25D0%25BE%25D1%2585%25D0%25BE%25D0%25B4%25D0%25B0%25D1%2585%2520%25D1%2584%25D0%25B8%25D0%25B7%25D0%25B8%25D1%2587%25D0%25B5%25D1%2581%25D0%25BA%25D0%25B8%25D1%2585%2520%25D0%25BB%25D0%25B8%25D1%2586%2520%25D0%25B7%25D0%25B0%25202024%2520%25D0%25B3%25D0%25BE%25D0%25B4%3A%2520%25D0%25BF%25D0%25BE%25D1%2580%25D1%258F%25D0%25B4%25D0%25BE%25D0%25BA%2520%25D0%25B7%25D0%25B0%25D0%25BF%25D0%25BE%25D0%25BB%25D0%25BD%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2520%25D0%25B8%2520%25D0%25BF%25D1%2580%25D0%25B5%25D0%25B4%25D1%2581%25D1%2582%25D0%25B0%25D0%25B2%25D0%25BB%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2520%25D0%25BD%25D0%25B0%25D0%25BB%25D0%25BE%25D0%25B3%25D0%25BE%25D0%25B2%25D1%258B%25D0%25BC%25D0%25B8%2520%25D0%25B0%25D0%25B3%25D0%25B5%25D0%25BD%25D1%2582%25D0%25B0%25D0%25BC%25D0%25B8%2520%25D0%25B2%25202025%2520%25D0%25B3%25D0%25BE%25D0%25B4%25D1%2583%25D0%25B3%25D0%25BB%25D0%25B0%25D0%25B2%25D0%25BD%25D1%258B%25D0%25B5%2520%25D0%25B1%25D1%2583%25D1%2585%25D0%25B3%25D0%25B0%25D0%25BB%25D1%2582%25D0%25B5%25D1%2580%25D1%258B%2520%25D0%25B8%2520%25D0%25B1%25D1%2583%25D1%2585%25D0%25B3%25D0%25B0%25D0%25BB%25D...&config=block&rid=a82f1a2c01b4a395065f87d3f5cf59d4&cscore0=$SQL&score0=16&cscore1=$XSS&score1=32&zone0=URL&id0=1010&var_name0=, client: 37.215.37.90, server: domen.name, request: "POST /event/09-01-svedeniya-o-dohodah-fizicheskih-lits-za-2024-god-poryadok-zapolneniya-i-predstavleniya-nalogovymi-agentami-v-2025-godu/%20target=_blank%20rel=%20noopener%20noreferrer%20%3E%D0%A1%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BE%20%D0%B4%D0%BE%D1%85%D0%BE%D0%B4%D0%B0%D1%85%20%D1%84%D0%B8%D0%B7%D0%B8%D1%87%D0
```

Copy and paste here the logs

```

**Additional details**

Whitelist rule : 
I read documentation. Check Regex. Rule looks able to wrok. But.... whitelist not triggered.
All other my whitelists rule works. But not this one =(
 
BasicRule wl:0 "mz:$URL_X:^[a-zA-Z/0-9%_-]*target[%A-Z0-9=]*_blank.*$|URL";

don't work for  request described above. In Nginx Log Section.

I didn't know why. I checked regex. Regex work. I was use regex rule for python.
Please help!) 

Add any other detail about the problem here.

**Comment by viiftw** [comment]
it uses PCRE regex format not python. I'm not very clear about regular expressions but when I tried with pcre your expression was not in the correct format

**Comment by wargio** [comment]
you can use regex101 and select PCRE2, when writing rules and whitelists containing regexes.

I strongly discourage using `wl:0` (see https://wargio.github.io/naxsi/whitelist.html#whitelist-ids) and instead whitelist the ids `wl:1010,xxx,yyy,...`

Try the following rule.

```
BasicRule wl:0 "mz:$URL_X:^[a-zA-Z\/0-9%_-]*target[%A-Z0-9=]*_blank.*$";
```

**Comment by LopEared** [comment]
> you can use regex101 and select PCRE2, when writing rules and whitelists containing regexes.
> 
> I strongly discourage using `wl:0` (see https://wargio.github.io/naxsi/whitelist.html#whitelist-ids) and instead whitelist the ids `wl:1010,xxx,yyy,...`
> 
> Try the following rule.
> 
> ```
> BasicRule wl:0 "mz:$URL_X:^[a-zA-Z\/0-9%_-]*target[%A-Z0-9=]*_blank.*$";
> ```

Issues the same. 
2024/12/19 18:17:07 [error] 2756494#2756494: *361061670 NAXSI_FMT: ip=93.125.107.24&server=xeli.by&uri=%2Fconference%2Fprakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025%2F%2520target%3D_blank%2520rel%3D%2520noopener%2520noreferrer%2520%253E%2522%25D0%259E%25D1%2581%25D0%25BD%25D0%25BE%25D0%25B2%25D0%25BD%25D1%258B%25D0%25B5%2520%25D0%25B8%25D0%25B7%25D0%25BC%25D0%25B5%25D0%25BD%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2520%25D0%259D%25D0%25B0%25D0%25BB%25D0%25BE%25D0%25B3%25D0%25BE%25D0%25B2%25D0%25BE%25D0%25B3%25D0%25BE%2520%25D0%25BA%25D0%25BE%25D0%25B4%25D0%25B5%25D0%25BA%25D1%2581%25D0%25B0%2520%25E2%2580%2593%25202025%2522%25C2%25A0%25C2%25A0%2520%25C2%25A0%25C2%25A0%25D0%25A3%25D1%2587%25D0%25B0%25D1%2581%25D1%2582%25D0%25B8%25D0%25B5%2520%25D0%25BF%25D0%25BB%25D0%25B0%25D1%2582%25D0%25BD%25D0%25BE%25D0%25B5%2C%2520%25D1%2581%25D1%2582%25D0%25BE%25D0%25B8%25D0%25BC%25D0%25BE%25D1%2581%25D1%2582%25D1%258C%25C2%25A0%2520%25D1%2583%25D1%2587%25D0%25B0%25D1%2581%25D1%2582%25D...&config=block&rid=a82d16b3a3968cbcd489e85a14c1fdf1&cscore0=$SQL&score0=8&cscore1=$XSS&score1=8&zone0=URL&id0=1007&var_name0=&zone1=URL&id1=1008&var_name1=, client: 93.125.107.24, server: xeli.by, request: "POST /conference/prakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025/%20target=_blank%20rel=%20noopener%20noreferrer%20%3E%22%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%9D%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE%20%D0%BA%D0%BE%D0%B4%D0%B5%D0%BA%D1%81%D0%B0%20%E2%80%93%202025%22%C2%A0%C2%A0%20%C2%A0%C2%A0%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%B5%20%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE%D0%B5,%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C%C2%A0%20%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D1%8F%20%D0%B2%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%201-%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%20%D0%B7%D0%B0%D0%BA%D0%B0%D
2024/12/19 18:27:48 [error] 2756494#2756494: *361093251 NAXSI_FMT: ip=46.216.179.204&server=xeli.by&uri=%2Fconference%2Fprakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025%2F%2520target%3D_blank%2520rel%3D%2520noopener%2520noreferrer%2520%253E%2522%25D0%259E%25D1%2581%25D0%25BD%25D0%25BE%25D0%25B2%25D0%25BD%25D1%258B%25D0%25B5%2520%25D0%25B8%25D0%25B7%25D0%25BC%25D0%25B5%25D0%25BD%25D0%25B5%25D0%25BD%25D0%25B8%25D1%258F%2520%25D0%259D%25D0%25B0%25D0%25BB%25D0%25BE%25D0%25B3%25D0%25BE%25D0%25B2%25D0%25BE%25D0%25B3%25D0%25BE%2520%25D0%25BA%25D0%25BE%25D0%25B4%25D0%25B5%25D0%25BA%25D1%2581%25D0%25B0%2520%25E2%2580%2593%25202025%2522%25C2%25A0%25C2%25A0%2520%25C2%25A0%25C2%25A0%25D0%25A3%25D1%2587%25D0%25B0%25D1%2581%25D1%2582%25D0%25B8%25D0%25B5%2520%25D0%25BF%25D0%25BB%25D0%25B0%25D1%2582%25D0%25BD%25D0%25BE%25D0%25B5%2C%2520%25D1%2581%25D1%2582%25D0%25BE%25D0%25B8%25D0%25BC%25D0%25BE%25D1%2581%25D1%2582%25D1%258C%25C2%25A0%2520%25D1%2583%25D1%2587%25D0%25B0%25D1%2581%25D1%2582%25D...&config=block&rid=413f581fda4e5d7b2e22a65e3403a2b7&cscore0=$SQL&score0=8&cscore1=$XSS&score1=8&zone0=URL&id0=1007&var_name0=&zone1=URL&id1=1008&var_name1=, client: 46.216.179.204, server: xeli.by, request: "POST /conference/prakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025/%20target=_blank%20rel=%20noopener%20noreferrer%20%3E%22%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%9D%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE%20%D0%BA%D0%BE%D0%B4%D0%B5%D0%BA%D1%81%D0%B0%20%E2%80%93%202025%22%C2%A0%C2%A0%20%C2%A0%C2%A0%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%B5%20%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE%D0%B5,%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C%C2%A0%20%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D1%8F%20%D0%B2%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%201-%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%20%D0%B7%D0%B0%D0%BA%D0%B0

I updated rule using  new rule: 

BasicRule wl:1001,1007,1008,1010,1011,1015,1303  "mz:$URL_X:^[a-zA-Z\/0-9%._-]*target[%A-Z0-9=]*_blank.*|URL";

**Comment by LopEared** [comment]
Can using advanced logging mode help me?

**Comment by wargio** [comment]
just to be sure, you are in blocking mode, right?

**Comment by LopEared** [comment]
yep.  In log output - config -> block

**Comment by wargio** [comment]
I'm sorry, i actually forgot about this detail when i replied the first time. NAXSI actually decodes all the url (multiple times) so when the regex is matched is not matched to the original url-encoded string but to the decoded string.

Example:
```
/conference/prakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025/%20target=_blank%20rel=%20noopener%20noreferrer%20%3E%22%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%9D%D0%B0%D0%BB%D0%BE%D0%B3%D0%BE%D0%B2%D0%BE%D0%B3%D0%BE%20%D0%BA%D0%BE%D0%B4%D0%B5%D0%BA%D1%81%D0%B0%20%E2%80%93%202025%22%C2%A0%C2%A0%20%C2%A0%C2%A0%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%B5%20%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D0%BE%D0%B5,%20%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C%C2%A0%20%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D1%8F%20%D0%B2%20%D0%BA%D0%BE%D0%BD%D1%84%D0%B5%D1%80%D0%B5%D0%BD%D1%86%D0%B8%D0%B8%20%D0%BD%D0%B0%201-%D0%B3%D0%BE%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D0%B5%D0%BB%D1%8F%20%D0%B7%D0%B0%D0%BA%D0%B0
```

internally becomes
```
/conference/prakticheskaya-konferentsiya-osnovnye-izmeneniya-nalogovogo-kodeksa-2025/ target=_blank rel= noopener noreferrer >"Основные изменения Налогового кодекса – 2025"     Участие платное, стоимость  участия в конференции на 1-го представителя зака
```

So your regex (and my previous one i suggested) didn't work because of this specific reason; so the correct regex that does work is:

```
BasicRule wl:1001,1007,1008,1010,1011,1015,1303  "mz:$URL_X:^[\w\/ _-]*target[\w=]+_blank.+$|URL";
```

**Comment by LopEared** [comment]
Okay. Thanks a lot for previous answer.

The same issue fro whitelist rule:
BasicRule wl:1501 "mz:$URL_X:^(\/)?(%2F)?wp-json(\/)?(%2F)?contact-form-7(\/)?(%2F)?v1(\/)?(%2F)?contact-forms(\/)?(%2F)?.*$|FILE_EXT";
Log:
2024/12/20 10:00:31 [error] 2984554#2984554: *352273255 NAXSI_FMT: ip=128.65.32.151&server=xeli.com&uri=%2Fwp-json%2Fcontact-form-7%2Fv1%2Fcontact-forms%2F78763%2Ffeedback&config=block&rid=48d82c54aef0f3c097539575dc5aa129&cscore0=$UPLOAD&score0=8&zone0=FILE_EXT&id0=1501&var_name0=your-attachment, client: X.x.3X.1X, server: xeli.com, request: "POST /wp-json/contact-form-7/v1/contact-forms/78763/feedback HTTP/2.0"

**Comment by wargio** [comment]
here is the same thing. the URL needs first to be decoded (because it gets encoded when logging), then you can generate the regex for that.

`BasicRule wl:1501 "mz:$URL_X:^/wp-json/contact-form-7/v1/contact-forms/\d+/feedback$|FILE_EXT"`

**Comment by LopEared** [comment]
> here is the same thing. the URL needs first to be decoded (because it gets encoded when logging), then you can generate the regex for that.
> 
> `BasicRule wl:1501 "mz:$URL_X:^/wp-json/contact-form-7/v1/contact-forms/\d+/feedback$|FILE_EXT"`

Strange. The log I provided already has a decoded query. And it seems to match my regular expression.

For clarity, please provide the decoded query here in the message.
So that I can understand where I went wrong.

I used this line to create the regular expression:
/wp-json/contact-form-7/v1/contact-forms/78763/feedback

**Comment by wargio** [comment]
if the url that generates that issue is ` /wp-json/contact-form-7/v1/contact-forms/78763/feedback` then you can just generate a regex like `/wp-json/contact-form-7/v1/contact-forms/\d+/feedback` which should match with that url.

**Comment by LopEared** [comment]
Yes. Your regular expression matches.
Mine matches this line too.

The problem is that this rule fails periodically.
I will test your rule.
But it seems to me that the problem will remain.
The tests will show.

Thank you very much, [wargio].

**Comment by wargio** [comment]
Ok, i confirm that is illegal, but then there is no way for you to define a regex url. i guess this can be patched.
