### ISSUE TITLE
Configuration File nginx.conf test failed

### ISSUE THREAD

**Issue by CSmithy123** [wargio/naxsi#27]
Hello,

Im getting an error previously seen under: https://github.com/nbs-system/naxsi/issues/593

I managed to get naxsi running on nginx 1.21.4 fine (pre pcre2) as i couldn't get it to work on any newer version of nginx. I noticed under https://github.com/nbs-system/naxsi/issues/618 that some merges have been reuploaded however i can't get this to work on nginx 1.23.1. Just to confirm naxsi_core.rules is included within the http context, and naxsi_rules is under location in nginx.conf.

Compiled Nginx from source with Naxsi bundled in (error message occurs when starting nginx) and logs aren't providing any more detail.

**Comment by wargio** [comment]
This is kinda weird, because according to the ci (https://github.com/wargio/naxsi/pull/18) and my server (which uses PCRE2), it does work.
can you share the configuration? what other errors spits out when you test the configuration?

**Comment by CSmithy123** [comment]
Hi wargio,

Just managed to figure out what was wrong. Thanks for the response :)

**Comment by wargio** [comment]
i guess i will close this then
