### ISSUE TITLE
nginx: [emerg] Naxsi-Config : Incorrect line MainRule

### ISSUE THREAD

**Issue by InvokerFury** [wargio/naxsi#40]
Hi Sir, i follow the guide install nginx and naxsi on rhel 8, but i got issue

nginx: [emerg] Naxsi-Config : Incorrect line MainRule rx:select|union|update|delete|insert|table|from|ascii|hex|unhex|drop|load_file|substr|group_concat|dumpfile (../naxsi-master/naxsi_src//naxsi_skeleton.c/973)... in /etc/nginx/naxsi_core.rules:23
nginx: configuration file /etc/nginx/nginx.conf test failed

nginx version: nginx/1.22.0
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-10) (GCC)
built with OpenSSL 1.1.1k  FIPS 25 Mar 2021
TLS SNI support enabled
configure arguments: --conf-path=/etc/nginx/nginx.conf --add-module=../naxsi-master/naxsi_src/ --error-log-path=/var/log/nginx                         /error.log --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-log-path=/v                         ar/log/nginx/access.log --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-tem                         p-path=/var/lib/nginx/uwsgi --lock-path=/var/lock/nginx.lock --pid-path=/var/run/nginx.pid --user=nginx --group=nginx --with-d                         ebug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http                         _auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition                         _module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_modul                         e --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module --                         prefix=/usr

could you help me please 

thanks

**Comment by wargio** [comment]
where do you import the file?

**Comment by InvokerFury** [comment]
I add naxsi like thid
--add-module=../naxsi-master/naxsi_src/

**Comment by wargio** [comment]
are you using this repository or the original one?

**Comment by InvokerFury** [comment]
Iam using this repository sir, let me try it again with clean file and this repo again.. i ll inform you asap..

Thanks sir

**Comment by InvokerFury** [comment]
hi sir,

it worked like a charm.. thanks
