### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dvershinin** [wargio/naxsi#51]
Hi,

Same question as [here](https://github.com/nbs-system/naxsi/issues/580#issuecomment-1272242955).
If this is the better-maintained fork, please tag a release version to reflect the changes. The last release tag was 2 years ago.

**Comment by wargio** [comment]
https://github.com/wargio/naxsi/releases/tag/1.4rc1

**Comment by wargio** [comment]
i will publish 1.4 once i finish some validation tests. probably this week.

**Comment by wargio** [comment]
https://github.com/wargio/naxsi/releases/tag/1.4 has been released. sorry for the delay.
