### ISSUE TITLE
unknown directive "MainRule" in /etc/nginx/naxsi_core.rules:22

### ISSUE THREAD

**Issue by saurin-tech** [wargio/naxsi#58]
Hi,
I just did a fresh install of Nginx with naxsi in a docker container image based on Debian.  I'm able to build the image but as soon as I run the container it  exits with the message `nginx: [emerg] unknown directive "MainRule" in /etc/nginx/naxsi_core.rules:22`.  The version of Nginx that I'm using is 1.23.2 and using the current master branch for the naxsi.

**Comment by wargio** [comment]
that means you either forgot to include the module or your built module was not installed, etc..

**Comment by saurin-tech** [comment]
That helped, thank you!
