### ISSUE TITLE
Latest libinjection cannot be used due broken embedding

### ISSUE THREAD

**Issue by wargio** [wargio/naxsi#61]
The latest changes on libinjection does not allow embedding.

https://github.com/libinjection/libinjection/issues/31

**Comment by rickygm** [comment]
Is the module still functional for now with Naxsi project?

**Comment by wargio** [comment]
yes, i have update till the latest usable commit

**Comment by wargio** [comment]
If they won't fix this, then i will just fork it and keep it synced with patches.

**Comment by rickygm** [comment]
> If they won't fix this, then i will just fork it and keep it synced with patches.

excellent, thanks for your effort 👍 , but I think this library is very important and the community will continue to maintain it.

by the way I share with you a link about a new technique to bypass the waf.

https://claroty.com/team82/research/js-on-security-off-abusing-json-based-sql-to-bypass-waf

**Comment by wargio** [comment]
those new keywords are very interesting

**Comment by wargio** [comment]
@rickygm most of that should be caught by these additional rules: https://github.com/wargio/naxsi/pull/64

**Comment by rickygm** [comment]
I am already testing, I think you are referring to this rule:

MainRule "str:c:c:msg:obvious windows path" "mz:ARGS|URL|BODY|$HEADERS_VAR:Cookie" "s:$TRAVERSAL:4" id:1203;

**Comment by wargio** [comment]
no, i'm referring to the changes in the commit

**Comment by rickygm** [comment]
ok , understood .
thank wargio.

**Comment by rickygm** [comment]
What classification did you give to the rules?

**Comment by wargio** [comment]
what you mean? the rules are simple, if i see any of those json functions being called, then i know is a SQLi

**Comment by rickygm** [comment]
I mean description

**Comment by wargio** [comment]
`"msg:json functions and operators"`

**Comment by rickygm** [comment]
ok, ready.
