### ISSUE TITLE
Json support

### ISSUE THREAD

**Issue by rickygm** [wargio/naxsi#68]
Hi wargio, just a clarification, is this json support that you added to be able to extract the log in this format? Do you have any example of how it would appear in the log?.

regards...

**Comment by wargio** [comment]
you can use the rid value to aggregate all the logs for each request

**Comment by rickygm** [comment]
I see a rid value in the log, but what exactly do you mean?

it would be interesting to have an api for log output.

I have a doubt, I am looking in the wiki how to activate the log in json format but I can't find it.

https://github.com/nbs-system/naxsi/wiki/json#json

**Comment by wargio** [comment]
what do you mean? you just enable it via `set $naxsi_json_log 1;`

```
set $naxsi_json_log 1;
location / {
    SecRulesEnabled;
    DeniedUrl "/RequestDenied";
    CheckRule "$SQL >= 8" BLOCK;
    CheckRule "$RFI >= 8" BLOCK;
    CheckRule "$TRAVERSAL >= 4" BLOCK;
    CheckRule "$XSS >= 8" BLOCK;
    root $TEST_NGINX_SERVROOT/html/;
    index index.html index.htm;
}
location /RequestDenied {
     return 412;
    # return 412;
}
```

for extended logs you also have to add `set $naxsi_extensive_log 1;`

**Comment by rickygm** [comment]
my doubt was with the rid value, now I understand it better , it is always good to consider adding the wiki.

**Comment by wargio** [comment]
i actually have to rewrite it completely. there are tons of info that are missing even before i forked.

**Comment by wargio** [comment]
i was and am the only one still developing this project. maybe in the future i will.

**Comment by rickygm** [comment]
ok my friend.

**Comment by wargio** [comment]
yeah. i never had the chance to finish rewriting the wiki.

**Comment by selivan** [comment]
@wargio Github wiki sucks anyway. If I move naxsi wiki content to .md files in `docs` and comb it up a little - would you be interested in such PR? Later that may be used to generate documentation on readthedocs.org or something similar.

**Comment by wargio** [comment]
we could also do that. could be nice to have a github.io page for the project which is generated by the docs

**Comment by rickygm** [comment]
I think it would be a good option

**Comment by selivan** [comment]
@wargio I will try to get to it this weekend.

**Comment by selivan** [comment]
@wargio Here it goes: https://github.com/wargio/naxsi/pull/94

**Comment by wargio** [comment]
Complete logs are now available here https://wargio.github.io/naxsi/ including logging https://wargio.github.io/naxsi/logs.html
