### ISSUE TITLE
Question to use the repo in docker enviroment?

### ISSUE THREAD

**Issue by farzadha2** [wargio/naxsi#74]
Hi
I was wondering how i could use your repo in my docker file?

Currently i have this on my docker file which im using the old naxsi 

```
FROM lscr.io/linuxserver/swag:latest
RUN apk update
RUN apk add --upgrade nginx-mod-http-naxsi
```
Thank you

**Comment by wargio** [comment]
i should probably write to the alpine distribution to ask them to diverge to use my repo.

**Comment by wargio** [comment]
the only thing you can do is create a Dockerfile and build the repo using their latest nginx

**Comment by bfren** [comment]
Do you have any docs for how to do that, i.e. to use the pre-compiled package from Alpine's repo, and then compile / configure it for this NAXSI?  Or does Nginx need to be compiled *with* NAXSI?

**Comment by wargio** [comment]
regarding alpine is kinda complicated (also why i haven't done it yet).
See more here: https://unix.stackexchange.com/questions/496755/how-to-get-the-source-code-used-to-build-the-packages-of-the-base-alpine-linux-d/509609#509609

**Comment by wargio** [comment]
You can grab the alpine releases from the nightly releases: https://github.com/wargio/naxsi/actions/runs/5310317532
or build it via docker
```bash
docker run --it --rm -v ./naxsi:/naxsi alpine:latest sh /naxsi/distros/alpine/build-ci.sh
```

**Comment by wargio** [comment]
i could try to backport and add the artifacts to 1.4
