### ISSUE TITLE
ip whitelist

### ISSUE THREAD

**Issue by rickygm** [wargio/naxsi#75]
Hi wargio, in this latest version of naxsi - nginx is showing me this message:

` nginx -t
nginx: [emerg] cannot add hash value in /etc/nginx/wafnaxsi/whitelists/ip_naxsi_whitelist:1
nginx: configuration file /etc/nginx/nginx.conf test failed`

 I don't know if it is due to nginx or naxsi?

ip_naxsi_whitelist

IgnoreIP 186.77.204.111;
IgnoreIP 190.92.159.48;

any idea?

**Comment by wargio** [comment]
that is indeed weird. let me add it to the test chain.

**Comment by wargio** [comment]
i can reproduce this. if the IP was already added previously, then you get that error. i should probably change the error.

**Comment by rickygm** [comment]
yes, I have many sites, and on one of them I was pointing the entire whitelists* directory and including it to ip_naxsi_whitelist.

please , closed this thread.
thank
