### ISSUE TITLE
Bundle libinjection to release tarball

### ISSUE THREAD

**Issue by dvershinin** [wargio/naxsi#79]
There is somewhat of an issue with `.tar.gz` in releases in that it requires to download libinjection manually.
I understand the convenience of using git submodules during development, but it is a big inconvenience to the end users.

**Comment by wargio** [comment]
actually there is a zip release (not tarball) with the dependencies on the release

**Comment by wargio** [comment]
https://github.com/wargio/naxsi/releases/download/1.4/naxsi-1.4-src-with-deps.zip

**Comment by wargio** [comment]
if you don't like zip files i can also make a gzipped tarball

**Comment by dvershinin** [comment]
Yes, tarball would be perfect.
